const startButton = document.getElementById('start-btn')
const studentButton = document.getElementById('student-btn')
const signUpButton = document.getElementById('signUp-btn')
const signInButton = document.getElementById('signIn-btn')
const signOutButton = document.getElementById('signOut-btn')
const classButton = document.getElementById('class-btn')
const homeworkButton = document.getElementById('homework-btn')
const paperButton = document.getElementById('paper-btn')
const queryButton = document.getElementById('query-btn')
const englishButton = document.getElementById('english-btn')
const hindiButton = document.getElementById('hindi-btn')
const mathsButton = document.getElementById('maths-btn')
const scienceButton = document.getElementById('science-btn')
const socialScienceButton = document.getElementById('social science-btn')
const englishButton1 = document.getElementById('english1-btn')
const hindiButton1 = document.getElementById('hindi1-btn')
const mathsButton1 = document.getElementById('maths1-btn')
const scienceButton1 = document.getElementById('science1-btn')
const socialScienceButton1 = document.getElementById('social science1-btn')
const englishButton2 = document.getElementById('english2-btn')
const hindiButton2 = document.getElementById('hindi2-btn')
const mathsButton2 = document.getElementById('maths2-btn')
const scienceButton2 = document.getElementById('science2-btn')
const socialScienceButton2 = document.getElementById('social science2-btn')
const questionContainerElement = document.getElementById('question-container')
const subjectContainerElement = document.getElementById('class-subjectContainer')
const subjectContainer1Element = document.getElementById('class-subjectContainer1')
const subjectContainer2Element = document.getElementById('class-subjectContainer2')
const englishContainerElement = document.getElementById('class-englishContainer')
const englishContainer1Element = document.getElementById('class-englishContainer1')
const previousPaperContainerElement = document.getElementById('class-previousPaperContainer')
const controlContainerElement = document.getElementById('control-container')
const controlContainer1Element = document.getElementById('control-container1')
const formContainerElement = document.getElementById('class-formContainer')

startButton.addEventListener('click', startApp)
signInButton.addEventListener('click',startTeacherApp)
homeworkButton.addEventListener('click', homeworkApp)
classButton.addEventListener('click', classApp)
englishButton.addEventListener('click', openMessage)
englishButton1.addEventListener('click', openMessage1)
paperButton.addEventListener('click', openSubjects)
englishButton2.addEventListener('click',openPaper)
studentButton.addEventListener('click', openProgress)
controlContainer1Element.classList.add('hide')


function startApp() {
startButton.classList.add('hide')
questionContainerElement.classList.add('hide')
classButton.classList.add('hide')
paperButton.classList.add('hide')
homeworkButton.classList.add('hide')
queryButton.classList.add('hide')
hindiButton.classList.add('hide')
englishButton.classList.add('hide')
mathsButton.classList.add('hide')
scienceButton.classList.add('hide') 
socialScienceButton.classList.add('hide') 
englishContainerElement.classList.add('hide')
englishContainer1Element.classList.add('hide')
previousPaperContainerElement.classList.add('hide')
controlContainerElement.classList.add('hide')
formContainerElement.classList.remove('hide')
}

function startTeacherApp(){
startButton.classList.add('hide')
questionContainerElement.classList.remove('hide')
classButton.classList.remove('hide')
paperButton.classList.remove('hide')
homeworkButton.classList.remove('hide')
queryButton.classList.remove('hide')
hindiButton.classList.add('hide')
englishButton.classList.add('hide')
mathsButton.classList.add('hide')
scienceButton.classList.add('hide') 
socialScienceButton.classList.add('hide') 
englishContainerElement.classList.add('hide')
englishContainer1Element.classList.add('hide')
previousPaperContainerElement.classList.add('hide')
controlContainerElement.classList.add('hide')
formContainerElement.classList.add('hide')
}

function classApp() {
    classButton.classList.add('hide')
    paperButton.classList.add('hide')
    homeworkButton.classList.add('hide')
    queryButton.classList.add('hide')
    subjectContainerElement.classList.remove('hide')
    questionContainerElement.classList.add('hide')
    hindiButton.classList.remove('hide')
    englishButton.classList.remove('hide')
    mathsButton.classList.remove('hide')
    scienceButton.classList.remove('hide') 
    socialScienceButton.classList.remove('hide')
    englishContainerElement.classList.add('hide')
    englishContainer1Element.classList.add('hide')
    previousPaperContainerElement.classList.add('hide')
   
  }

 function openMessage() {
  hindiButton.classList.add('hide')
  englishButton.classList.add('hide')
  mathsButton.classList.add('hide')
  scienceButton.classList.add('hide') 
  socialScienceButton.classList.add('hide')
  subjectContainerElement.classList.add('hide')
  englishContainerElement.classList.remove('hide')
  englishContainer1Element.classList.add('hide')
  previousPaperContainerElement.classList.add('hide')
  }

 function homeworkApp() {
  classButton.classList.add('hide')
  paperButton.classList.add('hide')
  homeworkButton.classList.add('hide')
  queryButton.classList.add('hide')
  subjectContainerElement.classList.add('hide')
  subjectContainer1Element.classList.remove('hide')
  questionContainerElement.classList.add('hide')
  hindiButton1.classList.remove('hide')
  englishButton1.classList.remove('hide')
  mathsButton1.classList.remove('hide')
  scienceButton1.classList.remove('hide') 
  socialScienceButton1.classList.remove('hide')
  englishContainer1Element.classList.add('hide')
  previousPaperContainerElement.classList.add('hide')
  }

  function openMessage1() {
    hindiButton1.classList.add('hide')
    englishButton1.classList.add('hide')
    mathsButton1.classList.add('hide')
    scienceButton1.classList.add('hide') 
    socialScienceButton1.classList.add('hide')
    subjectContainerElement.classList.add('hide')
    subjectContainer1Element.classList.add('hide')
    englishContainer1Element.classList.remove('hide')
    englishContainerElement.classList.add('hide')
    previousPaperContainerElement.classList.add('hide')
    }

    function openSubjects() {
    classButton.classList.add('hide')
    paperButton.classList.add('hide')
    homeworkButton.classList.add('hide')
    queryButton.classList.add('hide')
    subjectContainer2Element.classList.remove('hide')
    questionContainerElement.classList.add('hide')
    hindiButton2.classList.remove('hide')
    englishButton2.classList.remove('hide')
    mathsButton2.classList.remove('hide')
    scienceButton2.classList.remove('hide') 
    socialScienceButton2.classList.remove('hide')
    englishContainer1Element.classList.add('hide')
    englishContainerElement.classList.add('hide')
    }

    function openPaper() {
      previousPaperContainerElement.classList.remove('hide')
      hindiButton2.classList.add('hide')
      englishButton2.classList.add('hide')
      mathsButton2.classList.add('hide')
      scienceButton2.classList.add('hide') 
      socialScienceButton2.classList.add('hide')
      englishContainer1Element.classList.add('hide')
      englishContainerElement.classList.add('hide')
      subjectContainer2Element.classList.add('hide')
    }

    function openProgress() {
      controlContainer1Element.classList.remove('hide')
      startButton.classList.add('hide')
      controlContainerElement.classList.add('hide')
    }